from .classification import CLASSIFICATION_SYSTEM_PROMPT, CLASSIFICATION_USER_PROMPT
from .provision_identification import PROVISION_IDENTIFICATION_SYSTEM_PROMPT, PROVISION_IDENTIFICATION_USER_PROMPT
from .extraction import EXTRACTION_SYSTEM_PROMPT, EXTRACTION_USER_PROMPT
from .evidence import EVIDENCE_VERIFICATION_SYSTEM_PROMPT, EVIDENCE_VERIFICATION_USER_PROMPT

__all__ = [
    "CLASSIFICATION_SYSTEM_PROMPT",
    "CLASSIFICATION_USER_PROMPT",
    "PROVISION_IDENTIFICATION_SYSTEM_PROMPT",
    "PROVISION_IDENTIFICATION_USER_PROMPT",
    "EXTRACTION_SYSTEM_PROMPT",
    "EXTRACTION_USER_PROMPT",
    "EVIDENCE_VERIFICATION_SYSTEM_PROMPT",
    "EVIDENCE_VERIFICATION_USER_PROMPT",
]